name: Build & Release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Version Tag'
        required: true

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore ./src/Lod.RecordCollections.sln

    - name: Build
      run: dotnet build ./src/Lod.RecordCollections.sln -c Release --no-restore -p:DebugType=portable -p:CopyOutputSymbolsToOutputDirectory=true

    - name: Test
      run: dotnet test ./src/Lod.RecordCollections.sln -c Release --no-restore --no-build

    - name: IL Class/Record Conversion
      run: dotnet ./src/Lod.RecordCollections.IlAssembler/bin/Release/net6.0/Lod.RecordCollections.IlAssembler.dll D:\a\lod.recordcollections\lod.recordcollections\src\Lod.RecordCollections\bin\Release\netstandard2.0\Lod.RecordCollections.dll

    # This step shouldn't be required but cannot get pdb to build into netstandard2.0 directory and nuget pack won't pack without it
    - name: Copy Debug Files
      run: Copy-Item ./src/Lod.RecordCollections.IlAssembler/bin/Release/net6.0/Lod.RecordCollections.pdb -Destination ./src/Lod.RecordCollections/bin/Release/netstandard2.0

    - name: NuGet Pack (Tag)
      if: ${{ github.event.release.tag_name != null }}
      run: dotnet pack ./src/Lod.RecordCollections/Lod.RecordCollections.csproj -c Release --no-restore --include-symbols --no-build -p:Version=${{ github.event.release.tag_name }} -p:PackageVersion=${{ github.event.release.tag_name }}
    - name: NuGet Pack (Manual)
      if: ${{ inputs.tag != null }}
      run: dotnet pack ./src/Lod.RecordCollections/Lod.RecordCollections.csproj -c Release --no-restore --include-symbols --no-build -p:Version=${{ inputs.tag }} -p:PackageVersion=${{ inputs.tag }}

    - name: NuGet Push (Tag)
      if: ${{ github.event.release.tag_name != null }}
      run: dotnet nuget push ./src/Lod.RecordCollections/bin/Release/Lod.RecordCollections.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
    - name: NuGet Push (Manual)
      if: ${{ inputs.tag != null }}
      run: dotnet nuget push ./src/Lod.RecordCollections/bin/Release/Lod.RecordCollections.${{ inputs.tag }}.nupkg --api-key ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
