name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Version Tag'
        required: true

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set variables
      run: |
        version = $GITHUB_REF_NAME || ${{ inputs.tag }}

    - name: Restore dependencies
      run: dotnet restore ./src/Lod.RecordCollections.sln

    - name: Build
      run: dotnet build ./src/Lod.RecordCollections.sln -c Release --no-restore

    - name: Test
      run: dotnet test ./src/Lod.RecordCollections.sln -c Release --no-restore --no-build

    - name: Convert classes to records
      run: dotnet ./src/Lod.RecordCollections.IlAssembler/bin/Release/net6.0/Lod.RecordCollections.IlAssembler.dll D:\a\lod.recordcollections\lod.recordcollections\src\Lod.RecordCollections\bin\Release\netstandard2.0\Lod.RecordCollections.dll

    - name: NuGet Pack
      if: $GITHUB_REF_NAME != null
      run: dotnet pack ./src/Lod.RecordCollections/Lod.RecordCollections.csproj -c Release --no-restore --no-build /p:Version=$GITHUB_REF_NAME /p:PackageVersion=$GITHUB_REF_NAME
    - name: NuGet Pack
      if: ${{ inputs.tag != null }}
      run: dotnet pack ./src/Lod.RecordCollections/Lod.RecordCollections.csproj -c Release --no-restore --no-build /p:Version=${{ inputs.tag }} /p:PackageVersion=${{ inputs.tag }}
